indaclub/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :clubs
  resources :events

  resources :sessions, only: [:new, :create,:destroy]
  root "static#home"
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"

  resources :events do
    member do
      put "like", to: "events#upvote"
    end
  end

end

indaclub/app/models/attendee.rb
class Attendee < ActiveRecord::Base

  def attend
    @event = Event.find(params[:id])
    current_user.events << @event
    redirect_to @event
  end


end

indaclub/app/models/club.rb
class Club < ActiveRecord::Base
  mount_uploader :club_image, ClubImageUploader
  has_many :events
  belongs_to :user
  validates :name, presence:true
  # validates :location, presence:true
  # validates :description, presence:true, uniquness:true
end

indaclub/app/models/event.rb
class Event < ActiveRecord::Base
acts_as_votable
mount_uploader :event_image, EventImageUploader
  belongs_to :user
  belongs_to :club
  validates :name, presence:true
  validates :date, presence:true

  def score
    self.get_upvotes.size
  end

end

indaclub/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  mount_uploader :user_image, UserImageUploader
  acts_as_voter
  has_many :events 
  has_many :clubs
  validates :username, presence:true, uniqueness:true
  validates :email, presence:true, uniqueness:true 
end

indaclub/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?
  helper_method :authenticate
  helper_method :owns_event?

   def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end

   def logged_in?
     !!current_user
   end

   def authenticate
     unless logged_in?
       flash[:error] = "You must be logged in to access the content of this website"
       redirect_to "/"
     end
   end

   def authenticate_user(user)
       if user != current_user
         flash[:error] = "You are not authorized to do that."
         redirect_to root_path
       else 
         true
       end
     end

     def log_in(user)
         session[:user_id] = user.id
       end
     
  
end

indaclub/app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs

  def index
     @q = Club.ransack(params[:q]) 
     if params[:q].present?
      @q = Club.ransack(params[:q]) 
      @clubs = @q.result(district:true)
    else
    @clubs = Club.all
  end
end

  # GET /clubs/1
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :location, :description, :image, :club_image)
    end
end

indaclub/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
   @q = Event.ransack(params[:q]) 
   if params[:q].present?
    @q = Event.ransack(params[:q]) 
    @events = @q.result(district:true)
  else
    @events = Event.all 
  end
  

  end


  # GET /events/1
  def show

  end

  # GET /events/new
  def new
    @event = Event.new
    @event.liked_by @user
    @event.votes_for.size
  end

  # GET /events/1/edit
  def edit

  end

  # POST /events
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /events/1
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :ticketlink, :search, :event_image)
    end

    def upvote
      @event = Event.find(params[:id])
      @event.upvote_by current_user
      redirect_to @event
    end



end

indaclub/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:test] = "value"
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to clubs_path, notice: "logged in!"
    else
     
     render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "logged out!"
  end
end

indaclub/app/controllers/static_controller.rb
class StaticController < ApplicationController

end

indaclub/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :update, :upvote]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  redirect_to root_path unless authenticate_user(@user)

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end


  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to users_path
    else
      render:new
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    if @user = current_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  else
    redirect_to users_path
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :bio, :avatar, :password, :password_confirmation, :name, :user_image)
    end
end  

indaclub/app/helpers/application_helper.rb
module ApplicationHelper
end

indaclub/app/helpers/clubs_helper.rb
module ClubsHelper
end

indaclub/app/helpers/events_helper.rb
module EventsHelper
end

indaclub/app/helpers/sessions_helper.rb
module SessionsHelper
end

indaclub/app/helpers/static_helper.rb
module StaticHelper
end

indaclub/app/helpers/users_helper.rb
module UsersHelper
end

indaclub/app/views/application/_footer.html.erb
<footer>
  <div class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
        <p>© The last bad trip you'll ever have</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">facebook</a></li>
    
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

indaclub/app/views/application/_header.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">INDACLUB</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <% if current_user %>
        <li><%= current_user.username %></li>
       <!--  <li><%= link_to "Index", users_path %></li> -->
        <% end %>
        <li class="has-dropdown">
          <a href="#">Account</a>
          <ul class="dropdown">
            <% if logged_in? %>
            <li><%= link_to "PROFILE", user_path(current_user) %></li>
            <li><%= link_to "CLUBS", clubs_path %></li>
            <li><%= link_to "EVENTS", events_path %></li>
            <li><%= link_to "LOGOUT", logout_path, method: "delete" %></li>
            <% else %>
            <li><%= link_to "LOGIN", login_path %></li>
            <li><%= link_to "SIGN UP", new_user_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
      <li><%= link_to "HOME", root_path %></li>
      <li><%= image_tag "marcus_logo_white.png", class:"nav_image" %>
      </ul>
    </section>
  </nav>
</div>

indaclub/app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :club_image %><br />
    <%= f.file_field :club_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

indaclub/app/views/clubs/_other.html.erb
<tr>
  <td><%= club.name %></td>
  <td><%= club.location %></td>
  <td><%= club.description %></td>
  <td><%= club.image %></td>
  <td><%= link_to 'Show', club %></td>
  <% if current_user == club.user %>
  <td><%= link_to 'Edit', edit_club_path(club) %></td>
  <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>

indaclub/app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

indaclub/app/views/clubs/index.html.erb
<div class="row">
<div class="image">
  <div class="large-12 columns">
    <img id="cover-image" src="http://www.residentadvisor.net/photos/2012/es120528circol/dc_7.jpg"><br><br>
  </div>
  <h1></h1>
</div>
  </div>

  <h1>DON'T KNOW WHERE TO GO TONIGHT?</h1>

<p id="notice"><%= notice %></p>
<div class="search">
  <%= search_form_for @q do |f| %>
  <%= f.text_field :name_cont, :placeholder => "SEARCH OUR DATABASE OF CLUBS" %>
  <button id="home_buttons" type="submit">Search</button></div>
  <% end %>

</div>


<div class="row" data-equalizer>
 <% @clubs.each do |club| %>
  <div class="large-4 columns panel text-center" data-equalizer-watch>

  <%= image_tag(club.club_image.thumb) %>
    <%= link_to club.name, club %>

    </div>
    <% if current_user == club.user %>
    <li><%= link_to 'Edit', edit_club_path(club) %></li>
    <li><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>
 <% end %>

 </div>





<br>

<%= link_to 'New Club', new_club_path %>

indaclub/app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

indaclub/app/views/clubs/show.html.erb
<div class="row">
<div class="image">
  <div class="large-12 columns text-center">
    <%= image_tag @club.club_image.detail %><br>
  </div>
</div>
  </div>






<p id="notice"><%= notice %></p>


  <h2><%= @club.name %></h2>

<p>
  <strong>Location:</strong>
  <%= @club.location %>
</p>

<p>
 
  <%= @club.description %>
</p>

<p>
   
 </p>


<ul>
 <%= render @club.events %>
</ul>





<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

indaclub/app/views/events/_event.html.erb
<div class="large-4 columns panel text-center" data-equalizer-watch>
<%=link_to image_tag(event.event_image.thumb.url), event.event_image.url %>
 <h4> <%=link_to event.name, event %></h4>
  <p><%= event.date %></p>

  
  </div>

  <% if current_user == event.user %>
  <%= link_to 'Edit', edit_event_path(event) %>
  <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
  <li><%= link_to 'Edit', edit_event_path(event) %></li>
  <li><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>

indaclub/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :ticketlink %><br>
    <%= f.text_area :ticketlink %>
  </div>
  <div class="field">
    <%= f.label :event_image %><br />
    <%= f.file_field :event_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

indaclub/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

indaclub/app/views/events/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <img id="cover-image" src="http://www.essentialibiza.com/ecms/wp-content/uploads/2013/07/Pukka-Up.jpg"><br><br>
  </div>
</div>


<h1>IS THERE A DJ YOU WANT TO SEE?</h1>
<div class="search">
  <%= search_form_for @q do |f| %>
  <%= f.text_field :name_cont, :placeholder => "Check to see if your favourite DJ is playing" %>
  <div class="actions">
  <button id="home_buttons" type="submit">Search</button></div>
  <% end %>
</div>




<div class="row" data-equalizer>
 <%= render @events %>
</div>



<br>

<% @events.each do |event| %>
<% end %>



<%= link_to 'New Event', new_event_path %>

indaclub/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

indaclub/app/views/events/show.html.erb
<div class="row">
<div class="image">
  <div class="large-12 columns text-center">
    <%= image_tag @event.event_image.detail %><br>
  </div>
</div>
  </div>

<p>
  
  
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Buy Tickets Here:</strong>
  <%= @event.ticketlink %>
</p>

<p>
  <strong>Venue:</strong>
 <%= link_to @event.club.try(:name), @event.club %>
</p>

<%= link_to "Attending?", like_event_path(@event), method: :put %> 


<%= @event.score %>




<%= link_to 'Back', events_path %>

indaclub/app/views/layouts/application.html.erb
 <!DOCTYPE html>
 <html lang="en">
 <head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "" %>
  </title>
  <link rel="icon" type="browser.png" href="favicon-16x16.png" sizes="16x16" />
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="wrapper">
    <%=render "header" %>
    <main class="row">
      <%= yield %>
      
      
    </main>
    <div class="push"></div>
  </div>
  <div class="footer">
    <%=render "footer" %>
  </div>
  

</body>
</html> 

indaclub/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :username %><br>
  <%= f.text_field :username %>
</div>
<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :password %>
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</div>
<div class="field">
  <%= f.label :bio %><br>
  <%= f.text_area :bio %>
</div>
<div class="field">
   <%= f.label :user_image %><br />
   <%= f.file_field :user_image %>
 </div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

indaclub/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

indaclub/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Bio</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>



  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.bio %></td>
        <td><%= image_tag user.user_image.url %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

indaclub/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

indaclub/app/views/users/show.html.erb
<div class="row">
  <div class="large-10 columns text-center">
    <hr>
    <div class="row">
      <div class="large-5 columns">      
       <p> <%= image_tag @user.user_image.url %></p>
       <h3><strong>Events Attending:</strong></h3>
       <ul>
        <% @user.find_voted_items.each do |item| %>
        <li><%= link_to item.name, item %></li>
        <% end %>
      </ul>
    </div>
    <div class="large-5 columns">
      <h2><strong><%= @user.username %></strong></h2>

      <p id="Yo"><%= notice %></p>
      <h3> <strong><%= @user.email %></strong></h3>

      <h3><strong>Bio:</strong></h3>
      <strong><p><%= @user.bio %></p></strong>
    </p>

    <%= link_to 'Edit', edit_user_path(@user) %> |


    <%= link_to 'Back', users_path %>
  </div>
</div>
</div>
</div>